run:
  deadline: 2m

linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      - io/ioutil
      - github.com/aws/aws-sdk-go/*
  gocyclo:
    min-complexity: 10
  grouper:
    const-require-single-const: true
    import-require-single-import: true
    var-require-single-var: true
  lll:
    line-length: 80
    tab-width: 4
  tagliatelle:
    case:
      rules:
        json: snake
  wsl:
    allow-separated-leading-comment: true

linters:
  enable-all: true
  disable:
    - forbidigo # TODO: Enable when finished testing
    - gomnd
    - nestif
    - contextcheck
    - exhaustruct
    # default disabled linters
    - exhaustive
    - exhaustivestruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - godox
    - gofumpt
    - ifshort
    - ireturn
    - varnamelen
    # deprecated linters
    - golint
    - interfacer
    - maligned
    - scopelint
    # FIXME: temporary disabled linter until golangci-lint supports go 1.18
    - nolintlint
    # FIXME: temporary disabled linter due to bug: https://github.com/lufeee/execinquery/issues/3
    - execinquery
  fast: false

issues:
  include:
    - EXC0012
    - EXC0014
  exclude-rules:
    - path: _test\.go
      linters:
        - goerr113
        - gofmt
        - noctx
        # default unit test disabled linters
        - containedctx
        - cyclop
        - errcheck
        - forcetypeassert
        - gocognit
        - gocyclo
        - gosec
        - maintidx
        - paralleltest
        - testpackage
    - linters:
        - lll
      source: "// swagger:"
